packages:
- .
- ../liquidhaskell
explicit-setup-deps:
  "*": true
resolver: lts-5.5
extra-deps:
# - daemons-0.2.1
# # - liquid-fixpoint-0.5.0.1
# - liquidhaskell-cabal-0.1.1.0
# - located-base-0.1.1.0
# - dotgen-0.4.2
# - fgl-visualize-0.1.0.1
# - intern-0.9.1.4
# - aeson-0.11.3.0

- liquidhaskell-cabal-0.1.1.0
- located-base-0.1.1.0
