resolver: nightly-2016-05-21

explicit-setup-deps:
  "*": true

packages:
- .
- location:
    git: https://github.com/spinda/liquidhaskell-cabal.git
    commit: 7d24dd80e229a0b4291ef3a9c346e7ec31c33ac5
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: 3a9957985b63f7977f77badf2463c16ea7f54eb4
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 59f25fced058fdf8f0484dc9c176353160b4ad1f
  extra-dep: true
- location:
    git: https://github.com/christetreault/liquiddesugar
    commit: 792501fdbf75edbdeb496f9e16ee7ddf6fd2decf
  extra-dep: true

extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0
